### ISSUE TITLE
Crash: panicked at 'called `Result::unwrap()` on an `Err` value: RecvError(())', src\api\auth.rs:62:40

### ISSUE THREAD

**Issue by nhnb** [ceifa/steamworks.js#59] opened 2023-01-02 19:18 UTC
steamClient.localplayer.getName() works, but calling
`let ticket = await steamClient.auth.getSessionTicket();` never returns.

This issue happens on both Windows (see terminal log) and Linux. On some machines it started to work after some time without any obvious changes.

~~~~
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198[redacted] [API loaded no]
steamClient.localplayer.getName(): [redacted]

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError(())', src\api\auth.rs:62:40
stack backtrace:
   0:     0x7ff8ff0dc9f7 - napi_register_module_v1
   1:     0x7ff8ff0ab74b - <unknown>
   2:     0x7ff8ff0d2e91 - napi_register_module_v1
   3:     0x7ff8ff0deb6b - napi_register_module_v1
   4:     0x7ff8ff0de727 - napi_register_module_v1
   5:     0x7ff8ff0df68d - napi_register_module_v1
   6:     0x7ff8ff0df135 - napi_register_module_v1
   7:     0x7ff8ff0df07f - napi_register_module_v1
   8:     0x7ff8ff0df054 - napi_register_module_v1
   9:     0x7ff8ff172e85 - napi_register_module_v1
  10:     0x7ff8ff1730f3 - napi_register_module_v1
  11:     0x7ff8ff10fca1 - napi_register_module_v1
  12:     0x7ff8ff130ccd - napi_register_module_v1
  13:     0x7ff8ff169786 - napi_register_module_v1
  14:     0x7ff8ff16d155 - napi_register_module_v1
  15:     0x7ff8ff165a19 - napi_register_module_v1
  16:     0x7ff8ff167721 - napi_register_module_v1
  17:     0x7ff8ff0dbd1b - napi_register_module_v1
  18:     0x7ff930fe7614 - BaseThreadInitThunk
  19:     0x7ff932a426a1 - RtlUserThreadStart
~~~~

**Comment by ceifa** [comment] 2023-01-02 20:20
Which version of electron are you using? Probably a duplicate of #51

**Comment by nhnb** [comment] 2023-01-02 23:08
This error occurs on Electron 20.3.8. Chrome 104.0.5112.125 and Node 16.16.0.

With Electron 21, we get the same error message as mentioned in #51.

**Comment by ceifa** [comment] 2023-01-27 14:37
I'm not sure on why this is happening, but I made a simple change and should not panic anymore, instead it will throw an error. Can you test it and post the error message?

**Closed** 2024-05-03 22:24 UTC
